export const baseImages = '/assets/img/';
export const predefinedPath = baseImages + 'predefined/';

export const assistantNMSWatermark = baseImages + 'assistantNMSWatermark.png';
export const nmscdWatermark = baseImages + 'nmscdWatermark.png';

export const predefinedImages = [
    'Atlas.png',
    'BANNERICON.ASTRONAUT.png',
    'BANNERICON.CAMERA.png',
    'BANNERICON.COG.png',
    'BANNERICON.COMMUNITY.png',
    'BANNERICON.EXPLORERGUILD.png',
    'BANNERICON.FIEND.png',
    'BANNERICON.FLAG.png',
    'BANNERICON.FOURTH.png',
    'BANNERICON.GEK.png',
    'BANNERICON.GUN.png',
    'BANNERICON.KORVAX.png',
    'BANNERICON.LEAF.png',
    'BANNERICON.PAW.png',
    'BANNERICON.PORTAL.png',
    'BANNERICON.SHIELD.png',
    'BANNERICON.SKULL.png',
    'BANNERICON.TRADEGUILD.png',
    'BANNERICON.VYKEEN.png',
    'BANNERICON.WARP.png',
    'BANNERICON.WARRIORGUILD.png',
    'BANNERICONWIDE.AGT.png',
    'BANNERICONWIDE.AMINO.png',
    'BANNERICONWIDE.GALACTICHUB.png',
    'BANNERICONWIDE.QITANIANEMPIRE.png',
    'BANNERICONWIDE.UFT.png',
    'BUILDTAB_WALLART.png',
    'Class A.png',
    'Class B.png',
    'Class C.png',
    'Class S.png',
    'CLASSMINI.A.png',
    'CLASSMINI.B.png',
    'CLASSMINI.C.png',
    'CLASSMINI.png',
    'CLASSMINI.S.png',
    'CLASSMINI.SENTINEL.png',
    'CLASSMINI.X.png',
    'COMBAT1.png',
    'COMBAT6.png',
    'COMBATHEADER.png',
    'CURRENCY.NANITES.png',
    'CURRENCY.QUICKSILVER.png',
    'CURRENCY.UNITS.png',
    'FACTIONS.ASTRONAUT.OFF.png',
    'FACTIONS.EXPLORERGUILD.OFF.png',
    'FACTIONS.EXPLORERGUILD.ON.png',
    'FACTIONS.FOURTH.OFF.png',
    'FACTIONS.GEK.MSHOP.png',
    'FACTIONS.GEK.OFF.png',
    'FACTIONS.GEK.ON.png',
    'FACTIONS.KORVAX.MSHOP.png',
    'FACTIONS.KORVAX.OFF.png',
    'FACTIONS.KORVAX.ON.png',
    'FACTIONS.TRADEGUILD.OFF.png',
    'FACTIONS.TRADEGUILD.ON.png',
    'FACTIONS.VYKEEN.MSHOP.png',
    'FACTIONS.VYKEEN.OFF.png',
    'FACTIONS.VYKEEN.ON.png',
    'FACTIONS.WARRIORGUILD.OFF.png',
    'FACTIONS.WARRIORGUILD.ON.png',
    'gek.png',
    'korvax.png',
    'MISSION.ATLASPATH.MSHOP.png',
    'MISSION.ATLASPATH.OFF.png',
    'MISSION.ATLASPATH.ON.png',
    'MISSION.BOUNTYEASY.MSHOP.png',
    'MISSION.BOUNTYEASY.OFF.png',
    'MISSION.BOUNTYEASY.ON.png',
    'MISSION.BOUNTYHARD.MSHOP.png',
    'MISSION.BOUNTYHARD.OFF.png',
    'MISSION.BOUNTYHARD.ON.png',
    'MISSION.BOUNTYMEDIUM.MSHOP.png',
    'MISSION.BOUNTYMEDIUM.OFF.png',
    'MISSION.BOUNTYMEDIUM.ON.png',
    'MISSION.COMMUNITY.OFF.png',
    'MISSION.COMMUNITY.ON.png',
    'MISSION.DEPOTRAID.MSHOP.png',
    'MISSION.DEPOTRAID.OFF.png',
    'MISSION.DEPOTRAID.ON.png',
    'MISSION.ROBOTKILL.MSHOP.png',
    'MISSION.ROBOTKILL.OFF.png',
    'MISSION.ROBOTKILL.ON.png',
    'MISSION.SHIP.MSHOP.png',
    'MISSION.SHIP.OFF.png',
    'MISSION.SHIP.ON.png',
    'multitool.png',
    'PATCH1.png',
    'PATCH2.png',
    'PATCH3.png',
    'PATCH4.png',
    'PATCH5.png',
    'PATCH6.png',
    'SEASONLOCK.png',
    'STANDINGSLASH.EXPLORATION.png',
    'STANDINGSLASH.GEK.png',
    'STANDINGSLASH.KORVAX.png',
    'STANDINGSLASH.TRADE.png',
    'STANDINGSLASH.VYKEEN.png',
    'STANDINGSLASH.WAR.png',
    'SYSTEM.CONFLICTPIRATE.png',
    'SYSTEM.RACEGEK.png',
    'SYSTEM.RACEKORVAX.png',
    'SYSTEM.RACEVYKEEN.png',
    'SYSTEM.TRADING.png',
    'TITLEUNLOCKED.png',
    'Trading.png',
    'vykeen.png',
];